apiVersion: apps/v1

kind: Deployment

metadata:

  name: todo-deploy

  labels:

    app: todo-app

spec:

  replicas: 3

  selector:

    matchLabels:

      app: todo-app

  template:

    metadata:

      labels:

        app: todo-app

    spec:

      containers:

      - name: todo-app

        image: vikram5/todoapp:v1

        ports:

        - containerPort: 8000

